GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/63cd9f651a5d9243f662678e

###
DELETE http://localhost:3001/api/notes/63cd9f651a5d9243f662678e

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Test new note"
}

### unknown endpoint
GET http://localhost:3001/unknown